---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ethnode

resources:
  - configmaps.yaml
  - consensus-layer-statefulset.yaml
  - execution-layer-statefulset.yaml
  - metrics-exporter-deployment.yaml
  - rbac.yaml
  - service-accounts.yaml
  - services.yaml
  #- secrets.yaml # make your own like this
  #- ingresses.yaml # make your own like this
