---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: execution-layer
  labels:
    app.kubernetes.io/name: execution
  namespace: ethnode
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: consensus-layer
  labels:
    app.kubernetes.io/name: beacon
  namespace: ethnode