---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - https://raw.githubusercontent.com/argoproj/argo-cd/v2.10.4/manifests/install.yaml
  - self-manage-app.yaml       # GitOps self-management of this directory
  - dev-cluster.yaml           # Dev cluster object
  - kube-prometheus-stack.yaml # observability stack
  - grafana-dashboards.yaml    # grafana dashboards
  - fullnode.yaml              # full eth node deployment
#  - cert-manager.yaml          # cert-manager cluster issuer
#  - local-mount-storage.yaml   # local storage class

